-- =============================================
-- Author: Eulz Avancena (original); modified 2026-09-01
-- Description: sp_ReplicateSales took a single exact date (@petsa) and was
--              called once per individual date-batch from
--              POSDataManagementAutomation.cs's per-batch loop. Converted to
--              a @FromDate/@ToDate range so the C# side can replicate all
--              source rows for a Branch+Machine's whole selected date span
--              in ONE call, instead of re-running the delete+reinsert once
--              per distinct date within that span.
--
--              DateOrder (BatchSalesDetails) and Transdate (BatchSalesSummary)
--              are DATETIME columns -- kept the existing CAST(... AS DATE)
--              treatment, now compared with BETWEEN @FromDate AND @ToDate.
--              DateOpen (SalesTransactionSummary) and DateExecute
--              (POSZReadingTransactions) are already plain DATE columns, so
--              they compare directly against the DATE-typed range params.
-- =============================================

IF OBJECT_ID('dbo.sp_ReplicateSales', 'P') IS NOT NULL
    EXEC sp_rename 'dbo.sp_ReplicateSales', 'sp_ReplicateSales_OLD_09012026200000';
GO

CREATE PROCEDURE [dbo].[sp_ReplicateSales]
	@brcode char(3),
	@FromDate date,
	@ToDate date,
	@machinename varchar(20)
AS
BEGIN

	SET NOCOUNT ON;
	DELETE FROM [dbo].[BatchSalesDetails2]
	 WHERE BranchCode=@brcode
	and CAST(DateOrder as date) BETWEEN @FromDate AND @ToDate
	and MachineUsed=@machinename

	INSERT INTO  [dbo].[BatchSalesDetails2]
           ([SequenceNumber]
           ,[BranchCode]
           ,[ReferenceNo]
           ,[CashierTransNo]
           ,[ProductCode]
           ,[CategoryCode]
           ,[Barcode]
           ,[Description]
           ,[Cost]
           ,[OriginalSellingPrice]
           ,[SellingPrice]
           ,[QtySold]
           ,[PrevQty]
           ,[UnitMeasure]
           ,[DiscountRate]
           ,[DiscountTotal]
           ,[ChargeRate]
           ,[ChargeTotal]
           ,[TaxRate]
           ,[TaxTotal]
           ,[SubTotal]
           ,[Income]
           ,[isHold]
           ,[isConfirmed]
           ,[isCancelled]
           ,[isVoid]
           ,[isErrorCorrect]
           ,[isVat]
           ,[HoldBy]
           ,[CancelledBy]
           ,[VoidBy]
           ,[ProcessedBy]
           ,[TotalAmount]
           ,[Status]
           ,[DateOrder]
           ,[isUpload]
           ,[isPosted]
           ,[isCosting]
           ,[MachineUsed])
	SELECT [SequenceNumber]
           ,[BranchCode]
           ,[ReferenceNo]
           ,[CashierTransNo]
           ,[ProductCode]
           ,[CategoryCode]
           ,[Barcode]
           ,[Description]
           ,[Cost]
           ,[OriginalSellingPrice]
           ,[SellingPrice]
           ,[QtySold]
           ,[PrevQty]
           ,[UnitMeasure]
           ,[DiscountRate]
           ,[DiscountTotal]
           ,[ChargeRate]
           ,[ChargeTotal]
           ,[TaxRate]
           ,[TaxTotal]
           ,[SubTotal]
           ,[Income]
           ,[isHold]
           ,[isConfirmed]
           ,[isCancelled]
           ,[isVoid]
           ,[isErrorCorrect]
           ,[isVat]
           ,[HoldBy]
           ,[CancelledBy]
           ,[VoidBy]
           ,[ProcessedBy]
           ,[TotalAmount]
           ,[Status]
           ,[DateOrder]
           ,[isUpload]
           ,[isPosted]
           ,[isCosting]
           ,[MachineUsed]
	FROM BatchSalesDetails with(nolock)
	WHERE BranchCode=@brcode
	and CAST(DateOrder as date) BETWEEN @FromDate AND @ToDate
	and MachineUsed=@machinename

	DELETE FROM
	[dbo].[BatchSalesSummary2]
	WHERE BranchCode=@brcode
	AND CAST(Transdate as date) BETWEEN @FromDate AND @ToDate
	AND MachineUsed=@machinename

	INSERT INTO [dbo].[BatchSalesSummary2]
           ([BranchCode]
           ,[ReferenceNo]
           ,[CashierTransNo]
           ,[CustomerNo]
           ,[Invoice]
           ,[TotalItem]
           ,[TotalItemSold]
           ,[TotalItemCancelled]
           ,[TotalItemVoid]
           ,[TotalItemReturned]
           ,[TotalItemDiscount]
           ,[TotalVatableItems]
           ,[TotalSoldAmount]
           ,[TotalCancelledAmount]
           ,[TotalVoidAmount]
           ,[TotalReturnedAmount]
           ,[TotalDiscountAmount]
           ,[TotalCharge]
           ,[TotalUnitPrice]
           ,[TotalSellingPrice]
           ,[TotalTax]
           ,[TotalKilos]
           ,[SubTotal]
           ,[TotalAmount]
           ,[TotalIncome]
           ,[TotalVATSale]
           ,[TotalVATExemptSale]
           ,[TotalVatableSale]
           ,[PaymentType]
           ,[AdvancePayment]
           ,[AmountTendered]
           ,[AmountChange]
           ,[isFloat]
           ,[isHold]
           ,[isVoid]
           ,[isErrorCorrect]
           ,[OnHoldName]
           ,[VoidBy]
           ,[Transdate]
           ,[PreparedBy]
           ,[MachineUsed]
           ,[Posted]
           ,[Status]
           ,[isUpload]
           ,[isPosted]
           ,[DiscountType]
           ,[SeniorControlNo]
           ,[SeniorName]
           ,[SeniorDiscount]
           ,[PwdIDNo]
           ,[PwdName]
           ,[PwdDiscountAmount]
           ,[ZeroRatedSale])
	SELECT [BranchCode]
           ,[ReferenceNo]
           ,[CashierTransNo]
           ,[CustomerNo]
           ,[Invoice]
           ,[TotalItem]
           ,[TotalItemSold]
           ,[TotalItemCancelled]
           ,[TotalItemVoid]
           ,[TotalItemReturned]
           ,[TotalItemDiscount]
           ,[TotalVatableItems]
           ,[TotalSoldAmount]
           ,[TotalCancelledAmount]
           ,[TotalVoidAmount]
           ,[TotalReturnedAmount]
           ,[TotalDiscountAmount]
           ,[TotalCharge]
           ,[TotalUnitPrice]
           ,[TotalSellingPrice]
           ,[TotalTax]
           ,[TotalKilos]
           ,[SubTotal]
           ,[TotalAmount]
           ,[TotalIncome]
           ,[TotalVATSale]
           ,[TotalVATExemptSale]
           ,[TotalVatableSale]
           ,[PaymentType]
           ,[AdvancePayment]
           ,[AmountTendered]
           ,[AmountChange]
           ,[isFloat]
           ,[isHold]
           ,[isVoid]
           ,[isErrorCorrect]
           ,[OnHoldName]
           ,[VoidBy]
           ,[Transdate]
           ,[PreparedBy]
           ,[MachineUsed]
           ,[Posted]
           ,[Status]
           ,[isUpload]
           ,[isPosted]
           ,[DiscountType]
           ,[SeniorControlNo]
           ,[SeniorName]
           ,[SeniorDiscount]
           ,[PwdIDNo]
           ,[PwdName]
           ,[PwdDiscountAmount]
           ,[ZeroRatedSale]
	FROM BatchSalesSummary with(nolock)
	WHERE BranchCode=@brcode
	AND CAST(Transdate as date) BETWEEN @FromDate AND @ToDate
	AND MachineUsed=@machinename

	DELETE FROM [dbo].[SalesTransactionSummary2]
	WHERE BranchCode=@brcode
	AND DateOpen BETWEEN @FromDate AND @ToDate
	AND MachineUsed=@machinename


INSERT INTO  [dbo].[SalesTransactionSummary2]
           ([BranchCode]
           ,[CashierTransNo]
           ,[TransactionDate]
           ,[UserID]
           ,[BeginningCash]
           ,[BeginningSI]
           ,[EndingSI]
           ,[BeginningTransactionNo]
           ,[EndingTransactionNo]
           ,[BeginningReturnTransNo]
           ,[EndingReturnTransNo]
           ,[NextBeginningCash]
           ,[TransactionBegin]
           ,[NoOfSoldItem]
           ,[TotalSoldItem]
           ,[NoOfCancelledItem]
           ,[TotalCancelledItem]
           ,[NoOfVoidItem]
           ,[TotalVoidItem]
           ,[NoOfReturnedItem]
           ,[TotalReturnedSales]
           ,[NoOfDiscount]
           ,[TotalDiscount]
           ,[NoOfSCDisc]
           ,[TotalSCDisc]
           ,[NoOfPWDDisc]
           ,[TotalOfPWDDisc]
           ,[NoOfRegDisc]
           ,[TotalOfRegDisc]
           ,[NoOfCharges]
           ,[TotalCharge]
           ,[NoOfTaxItem]
           ,[TotalTax]
           ,[TotalSales]
           ,[TotalCashSales]
           ,[TotalCreditSales]
           ,[TotalActualCash]
           ,[TotalNetSales]
           ,[TotalCoins]
           ,[CashRemitted]
           ,[OpenBy]
           ,[ClosedBy]
           ,[DateClosed]
           ,[isOpen]
           ,[DateOpen]
           ,[isUpload]
           ,[Shortage]
           ,[Overage]
           ,[TotalVatableSales]
           ,[TotalVatExemptSales]
           ,[TotalNetSalesOfVat]
           ,[TotalVatAmount]
           ,[TotalZeroRatedSale]
           ,[VatAdjustment]
           ,[MachineUsed]
		   ,TotalNetSalesOrig
		   )

SELECT [BranchCode]
           ,[CashierTransNo]
           ,[TransactionDate]
           ,[UserID]
           ,[BeginningCash]
           ,[BeginningSI]
           ,[EndingSI]
           ,[BeginningTransactionNo]
           ,[EndingTransactionNo]
           ,[BeginningReturnTransNo]
           ,[EndingReturnTransNo]
           ,[NextBeginningCash]
           ,[TransactionBegin]
           ,[NoOfSoldItem]
           ,[TotalSoldItem]
           ,[NoOfCancelledItem]
           ,[TotalCancelledItem]
           ,[NoOfVoidItem]
           ,[TotalVoidItem]
           ,[NoOfReturnedItem]
           ,[TotalReturnedSales]
           ,[NoOfDiscount]
           ,[TotalDiscount]
           ,[NoOfSCDisc]
           ,[TotalSCDisc]
           ,[NoOfPWDDisc]
           ,[TotalOfPWDDisc]
           ,[NoOfRegDisc]
           ,[TotalOfRegDisc]
           ,[NoOfCharges]
           ,[TotalCharge]
           ,[NoOfTaxItem]
           ,[TotalTax]
           ,[TotalSales]
           ,[TotalCashSales]
           ,[TotalCreditSales]
           ,[TotalActualCash]
           ,[TotalNetSales]
           ,[TotalCoins]
           ,[CashRemitted]
           ,[OpenBy]
           ,[ClosedBy]
           ,[DateClosed]
           ,[isOpen]
           ,[DateOpen]
           ,[isUpload]
           ,[Shortage]
           ,[Overage]
           ,[TotalVatableSales]
           ,[TotalVatExemptSales]
           ,[TotalNetSalesOfVat]
           ,[TotalVatAmount]
           ,[TotalZeroRatedSale]
           ,[VatAdjustment]
           ,[MachineUsed]
		   ,[TotalNetSales]
	FROM [dbo].[SalesTransactionSummary] with(nolock)
	WHERE BranchCode=@brcode
	AND DateOpen BETWEEN @FromDate AND @ToDate
	AND MachineUsed=@machinename

	DELETE FROM [dbo].[POSZReadingTransactions2]
	WHERE BranchCode=@brcode
	AND DateExecute BETWEEN @FromDate AND @ToDate
	AND MachineUsed=@machinename
INSERT INTO [dbo].[POSZReadingTransactions2]
           ([BranchCode]
           ,[CounterNo]
           ,[TransactionNo]
           ,[MachineUsed]
           ,[BeginningBalance]
           ,[Debit]
           ,[Credit]
           ,[EndingBalance]
           ,[BeginningSINo]
           ,[EndingSINo]
           ,[BeginningReturnTransNo]
           ,[EndingReturnTransNo]
           ,[SoldItems]
           ,[CancelledItems]
           ,[VoidItems]
           ,[ReturnedItems]
           ,[VatItems]
           ,[DiscountItems]
           ,[SCDiscItems]
           ,[PWDDiscItems]
           ,[RegDiscItems]
           ,[TotalCashSales]
           ,[TotalCreditSales]
           ,[TotalSales]
           ,[TotalCancelledSales]
           ,[TotalVoidSales]
           ,[TotalReturnedSales]
           ,[TotalDiscount]
           ,[TotalSCDiscount]
           ,[TotalPWDDiscount]
           ,[TotalRegDiscount]
           ,[TotalVatSales]
           ,[VatExemptSale]
           ,[VatableSale]
           ,[VatInput]
           ,[ZeroRatedSale]
           ,[VatAdjustment]
           ,[DateExecute]
           ,[ExecuteBy]
           ,[TotalNetSales])
	SELECT [BranchCode]
           ,[CounterNo]
           ,[TransactionNo]
           ,[MachineUsed]
           ,[BeginningBalance]
           ,[Debit]
           ,[Credit]
           ,[EndingBalance]
           ,[BeginningSINo]
           ,[EndingSINo]
           ,[BeginningReturnTransNo]
           ,[EndingReturnTransNo]
           ,[SoldItems]
           ,[CancelledItems]
           ,[VoidItems]
           ,[ReturnedItems]
           ,[VatItems]
           ,[DiscountItems]
           ,[SCDiscItems]
           ,[PWDDiscItems]
           ,[RegDiscItems]
           ,[TotalCashSales]
           ,[TotalCreditSales]
           ,[TotalSales]
           ,[TotalCancelledSales]
           ,[TotalVoidSales]
           ,[TotalReturnedSales]
           ,[TotalDiscount]
           ,[TotalSCDiscount]
           ,[TotalPWDDiscount]
           ,[TotalRegDiscount]
           ,[TotalVatSales]
           ,[VatExemptSale]
           ,[VatableSale]
           ,[VatInput]
           ,[ZeroRatedSale]
           ,[VatAdjustment]
           ,[DateExecute]
           ,[ExecuteBy]
           ,[TotalNetSales]
	FROM [dbo].[POSZReadingTransactions] with(nolock)
	WHERE BranchCode=@brcode
	AND DateExecute BETWEEN @FromDate AND @ToDate
	AND MachineUsed=@machinename
END
GO

PRINT 'DEPLOYMENT COMPLETE: sp_ReplicateSales now takes @FromDate/@ToDate instead of a single @petsa.';
