SET NOCOUNT ON;
PRINT '=== sp_AddTransferOrderRequest: new SP for AddOrderSTS.cs saveAll() ===';
GO
-- Line items the caller (Orders/AddOrderSTS.cs, gridView1) wants saved for this transfer PO.
-- Replaces the per-row "INSERT INTO TransferOrderDetails VALUES(...)" loop that built the
-- statement by string concatenation and derived SeqNo from a C# counter. No SellingPrice here --
-- TransferOrderDetails has no such column; the grid only carries it for on-screen reference.
IF TYPE_ID('dbo.tt_TransferOrderLines') IS NULL
    CREATE TYPE dbo.tt_TransferOrderLines AS TABLE
    (
        ProductCode  char(5)        NOT NULL,
        ProductName  varchar(60)    NOT NULL,
        Qty          decimal(10,3)  NOT NULL,
        Units        varchar(10)    NOT NULL,
        Remarks      varchar(500)   NULL
    );
GO
IF OBJECT_ID('dbo.sp_AddTransferOrderRequest') IS NOT NULL
    DROP PROCEDURE dbo.sp_AddTransferOrderRequest;
GO
SET QUOTED_IDENTIFIER ON;
GO
-- =============================================
-- Author:      2026-08-08
-- Description: Saves a new Stock Transfer Order request (Orders/AddOrderSTS.cs, saveAll()) --
--              TransferOrderDetails lines + the TransferOrderSummary header, in one
--              transaction. PONumber is assumed already generated by the caller (unchanged --
--              out of scope for this rewrite).
--
-- Preserves the exact behavior of the C# it replaces:
--   - SeqNo is generated here (ROW_NUMBER over @Lines) instead of a C# loop counter.
--   - Remarks has CHAR(10)/CHAR(13) stripped inline on INSERT, instead of a separate UPDATE
--     statement run immediately after the insert loop (same end result, one less round trip).
--   - Status is always 'FOR APPROVAL' -- unlike sp_AddSalesOrderRequest (AddOrder.cs), this
--     form has no JFC/ApprovalSettings auto-approval check in the code it replaces.
--   - ApprovedBy / DateApproved / TimeApproved keep the legacy sentinel values the old code
--     produced: ApprovedBy as empty string, DateApproved as '19000101', TimeApproved as
--     '00:00:00' -- the old code passed '' and ' ' for date/time columns, which SQL Server
--     silently converts to those sentinels rather than erroring (verified against this DB:
--     CAST('' AS DATE) = CAST(' ' AS DATE) = 1900-01-01, CAST(' ' AS TIME) = 00:00:00). Not
--     changed to NULL here since that would be an observable behavior change beyond what was
--     asked.
--   - Notes is whatever the caller passes for richTextBox1.Text at save time -- in the existing
--     UI this control is cleared by add2() after each line is added, so in practice this is
--     usually blank unless the user typed something into it after adding their last line. Not a
--     bug introduced here; just carried over as-is.
-- =============================================
CREATE PROCEDURE [dbo].[sp_AddTransferOrderRequest]
    @parmpono              varchar(10),
    @parminitiatingbranch  char(3),
    @parmdestinationbranch char(3),
    @parmeffectivitydate   date,
    @parmrequestedby       varchar(50),
    @parmnotes             varchar(200),
    @parmordertype         varchar(10),
    @parmgroupcategory     varchar(120),
    @Lines                 dbo.tt_TransferOrderLines READONLY
AS
BEGIN
    SET NOCOUNT ON;

    BEGIN TRY
        BEGIN TRAN;

        IF NOT EXISTS (SELECT 1 FROM @Lines)
            THROW 59401, 'No product lines submitted for this transfer order.', 1;

        IF EXISTS (SELECT 1 FROM TransferOrderSummary WHERE PONumber = @parmpono AND InitiatingBranch = @parminitiatingbranch)
            THROW 59402, 'This PO number has already been saved.', 1;

        INSERT INTO TransferOrderDetails
            (PONumber, SeqNo, ProductCode, ProductName, Qty, Units, isValid, Remarks)
        SELECT
            @parmpono,
            ROW_NUMBER() OVER (ORDER BY (SELECT NULL)),
            ProductCode,
            ProductName,
            Qty,
            Units,
            0,
            REPLACE(REPLACE(ISNULL(Remarks,''), CHAR(10), ''), CHAR(13), '')
        FROM @Lines;

        DECLARE @totalqty decimal(18,3);
        SELECT @totalqty = SUM(Qty) FROM @Lines;

        INSERT INTO TransferOrderSummary
            (PONumber, InitiatingBranch, BranchCode, Qty, Status, Dateadded, Timeadded, EffectivityDate,
             RequestedBy, ApprovedBy, DateApproved, TimeApproved, Notes, Remarks, isProcess, OrderType, GroupCategory)
        VALUES
            (@parmpono, @parminitiatingbranch, @parmdestinationbranch, @totalqty, 'FOR APPROVAL',
             GETDATE(), CAST(GETDATE() AS TIME), @parmeffectivitydate,
             @parmrequestedby, '', '19000101', '00:00:00', @parmnotes, ' ', 0, @parmordertype, @parmgroupcategory);

        COMMIT TRAN;
    END TRY
    BEGIN CATCH
        IF XACT_STATE() <> 0 ROLLBACK TRAN;

        DECLARE @EMsg  NVARCHAR(4000) = ERROR_MESSAGE();
        DECLARE @ESev  INT            = ERROR_SEVERITY();
        DECLARE @ESt   INT            = ERROR_STATE();
        DECLARE @ELine INT            = ERROR_LINE();
        DECLARE @EProc NVARCHAR(128)  = ISNULL(ERROR_PROCEDURE(), 'sp_AddTransferOrderRequest');
        RAISERROR('Error in %s (line %d): %s', @ESev, @ESt, @EProc, @ELine, @EMsg);
    END CATCH
END
GO
PRINT 'DEPLOYMENT COMPLETE: sp_AddTransferOrderRequest created.';
