SET NOCOUNT ON;
PRINT '=== sp_AddSalesOrderRequest: new SP for AddOrder.cs saveAll() ===';
GO
-- Line items the caller (Orders/AddOrder.cs, gridView1) wants saved for this PO. Replaces the
-- per-row "INSERT INTO PurchaseOrderDetails VALUES(...)" loop that built the statement by string
-- concatenation and derived SeqNo from a C# counter.
IF TYPE_ID('dbo.tt_PurchaseOrderLines') IS NULL
    CREATE TYPE dbo.tt_PurchaseOrderLines AS TABLE
    (
        ProductCode  varchar(50)    NOT NULL,
        ProductName  varchar(50)    NOT NULL,
        Qty          decimal(18,3)  NOT NULL,
        Units        varchar(50)    NOT NULL,
        Remarks      varchar(250)   NULL,
        SellingPrice decimal(10,2)  NOT NULL
    );
GO
IF OBJECT_ID('dbo.sp_AddSalesOrderRequest') IS NOT NULL
    DROP PROCEDURE dbo.sp_AddSalesOrderRequest;
GO
SET QUOTED_IDENTIFIER ON;
GO
-- =============================================
-- Author:      2026-08-08
-- Description: Saves a new Sales Order request (Orders/AddOrder.cs, saveAll()) --
--              PurchaseOrderDetails lines + the PurchaseOrderSummary header, in one
--              transaction. PONumber is assumed already generated by the caller (unchanged --
--              out of scope for this rewrite).
--
-- Preserves the exact behavior of the C# it replaces:
--   - SeqNo is generated here (ROW_NUMBER over @Lines) instead of a C# loop counter.
--   - Remarks has CHAR(10)/CHAR(13) stripped inline on INSERT, instead of a separate UPDATE
--     statement run immediately after the insert loop (same end result, one less round trip).
--   - Status defaults to 'FOR APPROVAL', auto-approved to 'APPROVED' only when
--     CompanyProfile.CompanyName='JFC' AND ApprovalSettings has Module='AddSalesOrder'
--     isAuto=1 -- same two-table check GlobalCache.CompanyName + the ApprovalSettings query
--     performed in C#.
--   - ApprovedBy/DateApproved keep the legacy sentinel values the old code produced: ApprovedBy
--     as empty string, DateApproved as '19000101' (SQL Server's implicit conversion of an empty
--     string literal into DATETIME/DATE -- the old code passed '' for a datetime column, which
--     SQL Server silently converts to 1900-01-01 rather than erroring). Not changed to NULL here
--     since that would be an observable behavior change beyond what was asked; flagged for a
--     follow-up if NULL is actually what should happen for an unapproved order.
-- =============================================
CREATE PROCEDURE [dbo].[sp_AddSalesOrderRequest]
    @parmpono            varchar(50),
    @parmcustomerkey     varchar(50),
    @parmbranchcode      varchar(50),
    @parmeffectivitydate date,
    @parmrequestedby     varchar(50),
    @parmnotes           varchar(200),
    @parmordertype       varchar(50),
    @parmpaymenttype     varchar(10),
    @Lines               dbo.tt_PurchaseOrderLines READONLY
AS
BEGIN
    SET NOCOUNT ON;

    BEGIN TRY
        BEGIN TRAN;

        IF NOT EXISTS (SELECT 1 FROM @Lines)
            THROW 59301, 'No product lines submitted for this order.', 1;

        IF EXISTS (SELECT 1 FROM PurchaseOrderSummary WHERE PONumber = @parmpono)
            THROW 59302, 'This PO number has already been saved.', 1;

        INSERT INTO PurchaseOrderDetails
            (SeqNo, PONumber, ProductCode, ProductName, Qty, Units, isValid, Remarks, SellingPrice)
        SELECT
            ROW_NUMBER() OVER (ORDER BY (SELECT NULL)),
            @parmpono,
            ProductCode,
            ProductName,
            Qty,
            Units,
            0,
            REPLACE(REPLACE(ISNULL(Remarks,''), CHAR(10), ''), CHAR(13), ''),
            SellingPrice
        FROM @Lines;

        DECLARE @totalqty decimal(18,3);
        SELECT @totalqty = SUM(Qty) FROM @Lines;

        DECLARE @stat varchar(50) = 'FOR APPROVAL';
        IF EXISTS (SELECT 1 FROM CompanyProfile WHERE CompanyName = 'JFC')
        BEGIN
            IF EXISTS (SELECT 1 FROM dbo.ApprovalSettings WHERE Module = 'AddSalesOrder' AND isAuto = 1)
                SET @stat = 'APPROVED';
        END

        INSERT INTO PurchaseOrderSummary
            (PONumber, Customer, BranchCode, Qty, Status, Dateadded, EffectivityDate,
             RequestedBy, ApprovedBy, DateApproved, Notes, Remarks, isProcess, OrderType, PaymentType)
        VALUES
            (@parmpono, @parmcustomerkey, @parmbranchcode, @totalqty, @stat, GETDATE(), @parmeffectivitydate,
             @parmrequestedby, '', '19000101', @parmnotes, ' ', 0, @parmordertype, @parmpaymenttype);

        COMMIT TRAN;

        SELECT @stat AS Status;
    END TRY
    BEGIN CATCH
        IF XACT_STATE() <> 0 ROLLBACK TRAN;

        DECLARE @EMsg  NVARCHAR(4000) = ERROR_MESSAGE();
        DECLARE @ESev  INT            = ERROR_SEVERITY();
        DECLARE @ESt   INT            = ERROR_STATE();
        DECLARE @ELine INT            = ERROR_LINE();
        DECLARE @EProc NVARCHAR(128)  = ISNULL(ERROR_PROCEDURE(), 'sp_AddSalesOrderRequest');
        RAISERROR('Error in %s (line %d): %s', @ESev, @ESt, @EProc, @ELine, @EMsg);
    END CATCH
END
GO
PRINT 'DEPLOYMENT COMPLETE: sp_AddSalesOrderRequest created.';
